@default_files = ("std.tex");

# Use pdfLaTeX
$pdf_mode = 1;

# Compile glossaries with makeindex
add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
sub makeglo2gls {
    system("makeindex -s basic.gst -o '$_[0]'.gls '$_[0]'.glo");
}

# Compile indexes with xindy
$makeindex = "xindy %O -M texindy -M idxbfpage -C utf8 -L english -t %B.ilg -o %D %S";

