add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
sub makeglo2gls {
    system("makeindex -s basic.gst -o '$_[0]'.gls '$_[0]'.glo");
}

$makeindex = 'stem=`basename %S .idx`; makeindex %O `test -f ${stem}.ist && echo "-s ${stem}.ist"` -o %D %S';
