name: check-python

on:
  pull_request:
    paths:
      - "tools/**.py"
      - "pyrightconfig.json"
      - ".github/workflows/check-python.yml"
  push:
    paths:
      - "tools/**.py"
      - "pyrightconfig.json"
      - ".github/workflows/check-python.yml"

jobs:
  pyright:
    name: Pyright type check
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: install pyright
        run: npm install -g pyright

      - name: run pyright
        run: pyright
